### ISSUE TITLE
functions request

### ISSUE THREAD

**Issue by Szybet** [manilarome/squareup#10]
Its the best startpage on github, but its missing in my opinion 2 functions
selecting searches with up / down keys
stopping the animation, its eating too much gpu
Also sometimes it searches instead going to a link.
I would love to see this

**Comment by cybardev** [comment]
> Also sometimes it searches instead going to a link.

Maybe because you forgot to add `http://` or `https://` before. This is mentioned in the Readme.

I think it's out of the scope of a hobby project to add a prediction system that can differentiate links from regular searches. One "unclean" way to do this would be to assume it's a URL if it ends in `.com`, `.net`, `.org`, etc. but then what if people really just want to search those? A solution to that could be adding a quicksearch mode which only searches, or the reverse (a quicksearch module that always assumes URL). All this is extremely messy, too much work and would probably feel like a chore more than a hobby for the dev.

> stopping the animation

Yes, I want this. Not because of usage tho, cuz I spend very little time in the search page so a slight spike in GPU usage doesn't hurt. It could be because it's distracting.

> selecting searches with up / down keys

Also yes, this would be really useful.
