### ISSUE TITLE
modularity

### ISSUE THREAD

**Issue by mxrixs** [manilarome/squareup#7]
I'd really love it if you could make the whole thing modular, so using single pieces of code/functionality for own projects becomes more simple. Of course I am in no place to demand this but the simple fact, that you put it on git only shows you want other people to use it. My specific interests would be the quicksearch alorithm and maybe trying to understanding how you made the background

**Comment by manilarome** [comment]
>  you put it on git only shows you want other people to use it.

Nope haha. This is just my hobby, I don't really expect people to use my projects. It's in here because of version control. And it's much safer here, who knows when my hard drive decided to just die.

> My specific interests would be the quicksearch alorithm and maybe trying to understanding how you made the background

I think I'll just explain it to you. First, I declared the `quick search obj` in  config.js: https://github.com/manilarome/squareup/blob/dde2edd426c1e352633820e2b09aa0537f66d51e/js/config.js#L25-L54

Then `search-query-send.js`, will retrieve the quick search object: https://github.com/manilarome/squareup/blob/dde2edd426c1e352633820e2b09aa0537f66d51e/js/search-query-send.js#L4

`search-query-send.js` is responsible for 'searching' on the web. And it's also the one that checks if the search query is a quick search or specifically have a search prefix like `r/`, `e/`, etc. : https://github.com/manilarome/squareup/blob/dde2edd426c1e352633820e2b09aa0537f66d51e/js/search-query-send.js#L20-L49

Yeah, that's the gist of it. You can understand it, my code isn't that bad(i guess so lol). Anyway, goodluck!
